title: Software Tools from Atomistics to Phase Diagrams 
author: Jan Janssen
logo: images/logo_dark.png

execute:
  execute_notebooks           : off

html:
    extra_navbar              : Powered by <a href="https://pyiron.org">pyiron</a>

repository:
    url                       : https://github.com/pyiron/potentials-workshop-2021
    path_to_book              : ""

launch_buttons:
  notebook_interface          : jupyterlab
  binderhub_url               : https://mybinder.org
