channels:
  - conda-forge
dependencies:
  - cython
  - libsass
  - jupytext
  - beautifulsoup4 =4.9.3
  - click =7.1.2
  - sphinx =2.4.4
  - pybtex
  - jupyter_sphinx
  - jupyter-cache =0.4.1
  - linkify-it-py =1.0.1
  - sphinxcontrib-bibtex
  - markdown-it-py
  - myst-parser
  - myst-nb =0.12.0
  - nbconvert =5.6.1
  - nested-lookup =0.2.22
  - nest-asyncio
  - async_generator
  - nbclient
  - nbdime
  - soupsieve =2.2
  - sphinx-copybutton
  - sphinx-book-theme =0.0.40
  - sphinx-comments =0.0.3
  - sphinx-panels =0.5.2
  - sphinx-thebe =0.0.7
  - sphinx-togglebutton =0.2.2
  - sqlalchemy =1.3.23
  - uc-micro-py =1.0.1
  - pydata-sphinx-theme
  - matplotlib =3.2.1