channels:
- conda-forge
dependencies:
- python
- pyiron =0.4.0 
- sphinxdft =2.7.0
- atomicrex =1.0.1
- runner =1.2
- lammps =2021.02.10=*openmpi*_4
- pyiron_atomistics =0.2.4
- pyiron-data =0.0.10
- nglview =2.7.7
- structdbrest =0.0.1
- papermill
- pip
- pip:
    - pyace-lite
