name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CONDA_PREFIX: /usr/share/miniconda/

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
        environment-file: .ci_support/environment.yml
        auto-activate-base: false
    - run: rm README.md CODE_OF_CONDUCT.md
    - name: Install Jupyterbook
      shell: bash -l {0}
      run: |
        pip install git+https://github.com/ExecutableBookProject/jupyter-book
        jupyter-book build . --path-output public
    - run: mv public/_build/html public_html
    - run: touch public_html/.nojekyll
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: public_html # The folder the action should deploy.
        CLEAN: true
